version: '3'
services:
  test1:
    image: c5725fbe9e3c
    command: ["./build.sh"]

  test2:
    image: c5725fbe9e3c
    command: ["./build.sh"]

  test3:
    image: c5725fbe9e3c
    command: ["./build.sh"]


